REST_HR = 45
MAX_HR = 190

HISTORY_DAYS = 365

MIN_SESSION_MIN = 20.0
MIN_SESSION_KM = 3.2
MIN_LONG_KM = 6.0
MIN_QUALITY_KM = 4.0

EASY_OK_THRESHOLD = -20
LONG_OK_THRESHOLD = -10
QUALITY_OK_THRESHOLD = -5

LOCAL_TZ = "Europe/Paris"
